[mainwindow]
pos=@Point(214 109)
size=@Size(1000 536)
workingDirectory=/home/admin/\x392\x3af\x3bd\x3c4\x3b5\x3bf

[options]
VideoPlayerParameters={0} --sub-file {1}
VideoPlayerPath=/usr/bin/vlc
filterSearchLang="bre,ger,ell"
interfaceLang=unknown
subtitleName=SAME_ONLINE
uploadLanguage=unknown
whereToDownload=SAME_FOLDER
whereToDownloadFolder=
