#!/usr/bin/env bash

kernel="$1"
[[ -n $kernel ]] || exit 0

# use already installed kernel if it exists
[[ ! -f $KERNELDESTINATION ]] || kernel="$KERNELDESTINATION"

bootdir="$(bootctl -x)"
keypairs=("$bootdir"/EFI/MOK.key "$bootdir"/EFI/MOK.crt)

for (( i=0; i<${#keypairs[@]}; i+=2 )); do
    key="${keypairs[$i]}" cert="${keypairs[(( i + 1 ))]}"
    if ! sbverify --cert "$cert" "$kernel" &>/dev/null; then
        sbsign --key "$key" --cert "$cert" --output "$kernel" "$kernel"
    fi
done

/usr/bin/grub_cfg_upd.sh # update grub.cfg with latest kernel versions
