[Filters]
ExactMatch=false
Interval=0
ShowDowngraded=true
ShowInstalled=true
ShowReinstalled=true
ShowRemoved=true
ShowUpgraded=true

[Table]
actionColumnWidth=55
dateColumnWidth=267
packageColumnWidth=140
versionColumnWidth=314

[Window]
height=600
widht=800
x-position=545
y-position=166
