# see cloneup.sh-exclude.conf(5) for the correct syntax to exclude files/dirs
#
# for clarity, put your entries here (above the default entries below), e.g.
#-/home/<user>/Music/*

# sometimes copied journals are corrupt and kernel crashes during boot
-/var/log/journal/

# DEFAULT ENTRIES - DON'T CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
# According to the Filesystem Hierarchy Standard (FHS) the following directories
# contain data that is temporary and used while the system is running and will
# be deleted when the system boots. Thus, they are excluded from cloning.
-/dev/*
-/proc/*
-/run/*
-/sys/*
-/tmp/*
-/media/*
-/mnt/*
-/var/cache/*
-/var/lock/*
-/var/run/*
