# maps filesystem names of 'parted' command to 'mkfs' command
#
# fields are separated by colon (:)
#
# first field    : 'parted' filesystem
# second field   : 'mkfs' command for filesystem
# last two fields: min & max sector or block size respectively (if any of them
#                  are zero the page size is assumed)
#
# to support comments after the end of a line the last field MUST be delimited
# by a colon

btrfs:mkfs.btrfs -q -f:4096:4096:      # no subvolumes supported!
ext2:mkfs.ext2 -c -q -F:1024:65536
ext3:mkfs.ext3 -c -q -F:1024:65536
ext4:mkfs.ext4 -c -q -F:1024:65536
fat16:mkfs.fat -c -I -F16:512:32768
fat32:mkfs.fat -c -I -F32:512:32768
hfs+:mkfs.hfsplus:4096:4096:           # filesystem is case insensitive
hfsx:mkfs.hfsplus -s:4096:4096:        # filesystem is case sensitive
jfs:mkfs.jfs -c -q:512:4096
linux-swap(v1):mkswap -c -q -f
nilfs2:mkfs.nilfs2 -c -q -f:1024:32768
ntfs:mkfs.ntfs -Q -q -F:256:4096:      # -Q: quick format else it takes ages
udf:mkfs.udf --utf8:512:32768
xfs:mkfs.xfs -q -f:512:32768
