# The following are brief explanations based on
# https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html
#
# (defaults in brackets)
# 
# /sys/power/mem_sleep (file that contains suspend variants)
#     s2idle : suspend-to-idle aka freeze, light-weight variant of suspend
#     shallow: standby, ACPI S1
#     [deep] : suspend-to-RAM, aka STR or S2RAM, ACPI S3
#    
# /sys/power/disk (file that contains hibernation modes)
#     [platform] : special low-power state, i.e. ACPI S4
#     shutdown   : power off system
#     reboot     : useful for diagnostics mostly
#     suspend    : hybrid sleep (suspend), default value from /sys/power/mem_sleep
#     test_resume: diagnostic operation
#
# /sys/power/state (file that contains sleep states)
#     freeze : suspend-to-idle aka S2I or S2Idle, light-weight variant of suspend
#     standby: standby, ACPI S1
#     mem    : suspend, default value from /sys/power/mem_sleep
#     disk   : hibernation, default value from /sys/power/disk

[Sleep]
AllowSuspend=yes
AllowHibernation=yes
AllowSuspendThenHibernate=yes
AllowHybridSleep=yes

MemorySleepMode=deep shallow s2idle
HibernateMode=platform shutdown suspend
SuspendState=standby freeze mem # mem is last as it doesn't work on old Acer 
                                # Aspire ES 15 laptop

HibernateDelaySec=50min
