[General]
geometry = @ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\x32\0\0\0!\0\0\aX\0\0\x3\xdb\0\0\x1\x37\0\0\0>\0\0\aS\0\0\x3\xd6\0\0\0\0\0\0\0\0\a\x80\0\0\x1\x37\0\0\0>\0\0\aS\0\0\x3\xd6)

[FullScreen]
pos = @Point(560 1010)
screen = @Rect(0 0 1920 1080)
wide = false

[MainWindow]
QtStyle = System's default
adv-controls = 4
bgSize = @Size(1565 775)
pl-dock-status = true
playlist-visible = false
playlistSize = @Size(-1 -1)
status-bar-visible = true

[Preferences]
geometry = @ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2+\0\0\0\x8c\0\0\x5T\0\0\x3i\0\0\x2\x30\0\0\0\xa9\0\0\x5O\0\0\x3\x64\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x30\0\0\0\xa9\0\0\x5O\0\0\x3\x64)

