TeamViewer User Settings
# It is not recommended to edit this file manually


[int32] ColorScheme = 2
[int32] LastCorrectorRun = 1
[int32] MainWindowSize = 921 494 122 195
[int32] MsgBoxDontShow\QuitWithAutostart = 1
