# remove all build files, the build directory is the one specified in pamac.conf
[Unit]
Requires=pacman-filesdb-refresh.service
After=pacman-filesdb-refresh.service

[Service]
ExecStart=
ExecStart=/usr/bin/pamac clean --no-confirm --verbose --build-files --keep 0
